[package]
name = "collapse_messenger"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
rand = "0.8"

[dev-dependencies]

[[bin]]
name = "repl"
path = "src/bin/repl.rs"
